# specify base image that we want to extend
FROM kartoza/postgis:12.1
# set environment variables that we want to change
ENV POSTGRES_USER=marius
ENV POSTGRES_PASS=password
ENV POSTGRES_DBNAME=marius-postgis